// Generated by Dagger (https://dagger.dev).
package com.kipreev.aston_final_project.data.network.repo;

import com.kipreev.aston_final_project.data.network.api.CharacterApi;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MainRepositoryImpl_Factory implements Factory<MainRepositoryImpl> {
  private final Provider<CharacterApi> apiProvider;

  public MainRepositoryImpl_Factory(Provider<CharacterApi> apiProvider) {
    this.apiProvider = apiProvider;
  }

  @Override
  public MainRepositoryImpl get() {
    return newInstance(apiProvider.get());
  }

  public static MainRepositoryImpl_Factory create(Provider<CharacterApi> apiProvider) {
    return new MainRepositoryImpl_Factory(apiProvider);
  }

  public static MainRepositoryImpl newInstance(CharacterApi api) {
    return new MainRepositoryImpl(api);
  }
}
