// Generated by Dagger (https://dagger.dev).
package com.kipreev.aston_final_project.presentation.activities;

import com.kipreev.aston_final_project.presentation.viewmodels.characters.CharacterInfoViewModel;
import com.kipreev.aston_final_project.presentation.viewmodels.characters.CharactersListViewModel;
import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;
import javax.inject.Provider;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MainActivity_MembersInjector implements MembersInjector<MainActivity> {
  private final Provider<CharactersListViewModel> charactersListViewModelProvider;

  private final Provider<CharacterInfoViewModel> characterInfoViewModelProvider;

  public MainActivity_MembersInjector(
      Provider<CharactersListViewModel> charactersListViewModelProvider,
      Provider<CharacterInfoViewModel> characterInfoViewModelProvider) {
    this.charactersListViewModelProvider = charactersListViewModelProvider;
    this.characterInfoViewModelProvider = characterInfoViewModelProvider;
  }

  public static MembersInjector<MainActivity> create(
      Provider<CharactersListViewModel> charactersListViewModelProvider,
      Provider<CharacterInfoViewModel> characterInfoViewModelProvider) {
    return new MainActivity_MembersInjector(charactersListViewModelProvider, characterInfoViewModelProvider);
  }

  @Override
  public void injectMembers(MainActivity instance) {
    injectCharactersListViewModel(instance, charactersListViewModelProvider.get());
    injectCharacterInfoViewModel(instance, characterInfoViewModelProvider.get());
  }

  @InjectedFieldSignature("com.kipreev.aston_final_project.presentation.activities.MainActivity.charactersListViewModel")
  public static void injectCharactersListViewModel(MainActivity instance,
      CharactersListViewModel charactersListViewModel) {
    instance.charactersListViewModel = charactersListViewModel;
  }

  @InjectedFieldSignature("com.kipreev.aston_final_project.presentation.activities.MainActivity.characterInfoViewModel")
  public static void injectCharacterInfoViewModel(MainActivity instance,
      CharacterInfoViewModel characterInfoViewModel) {
    instance.characterInfoViewModel = characterInfoViewModel;
  }
}
