// Generated by Dagger (https://dagger.dev).
package com.kipreev.aston_final_project.domain.characters;

import com.kipreev.aston_final_project.data.network.repo.MainRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetAllCharactersUseCase_Factory implements Factory<GetAllCharactersUseCase> {
  private final Provider<MainRepository> mainRepositoryProvider;

  public GetAllCharactersUseCase_Factory(Provider<MainRepository> mainRepositoryProvider) {
    this.mainRepositoryProvider = mainRepositoryProvider;
  }

  @Override
  public GetAllCharactersUseCase get() {
    return newInstance(mainRepositoryProvider.get());
  }

  public static GetAllCharactersUseCase_Factory create(
      Provider<MainRepository> mainRepositoryProvider) {
    return new GetAllCharactersUseCase_Factory(mainRepositoryProvider);
  }

  public static GetAllCharactersUseCase newInstance(MainRepository mainRepository) {
    return new GetAllCharactersUseCase(mainRepository);
  }
}
