// Generated by Dagger (https://dagger.dev).
package com.kipreev.aston_final_project.domain.characters;

import com.kipreev.aston_final_project.data.network.repo.MainRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetCharacterInfoUseCase_Factory implements Factory<GetCharacterInfoUseCase> {
  private final Provider<MainRepository> mainRepositoryProvider;

  public GetCharacterInfoUseCase_Factory(Provider<MainRepository> mainRepositoryProvider) {
    this.mainRepositoryProvider = mainRepositoryProvider;
  }

  @Override
  public GetCharacterInfoUseCase get() {
    return newInstance(mainRepositoryProvider.get());
  }

  public static GetCharacterInfoUseCase_Factory create(
      Provider<MainRepository> mainRepositoryProvider) {
    return new GetCharacterInfoUseCase_Factory(mainRepositoryProvider);
  }

  public static GetCharacterInfoUseCase newInstance(MainRepository mainRepository) {
    return new GetCharacterInfoUseCase(mainRepository);
  }
}
