// Generated by Dagger (https://dagger.dev).
package com.kipreev.aston_final_project.presentation.viewmodels.characters;

import com.kipreev.aston_final_project.domain.characters.GetCharacterInfoUseCase;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class CharacterInfoViewModel_Factory implements Factory<CharacterInfoViewModel> {
  private final Provider<GetCharacterInfoUseCase> getCharacterInfoUseCaseProvider;

  public CharacterInfoViewModel_Factory(
      Provider<GetCharacterInfoUseCase> getCharacterInfoUseCaseProvider) {
    this.getCharacterInfoUseCaseProvider = getCharacterInfoUseCaseProvider;
  }

  @Override
  public CharacterInfoViewModel get() {
    return newInstance(getCharacterInfoUseCaseProvider.get());
  }

  public static CharacterInfoViewModel_Factory create(
      Provider<GetCharacterInfoUseCase> getCharacterInfoUseCaseProvider) {
    return new CharacterInfoViewModel_Factory(getCharacterInfoUseCaseProvider);
  }

  public static CharacterInfoViewModel newInstance(
      GetCharacterInfoUseCase getCharacterInfoUseCase) {
    return new CharacterInfoViewModel(getCharacterInfoUseCase);
  }
}
